Update Logo And Data Istari Vision
multiversx/mx-assets pull request #1858
Opened 2023-12-19 13:10 UTC by CristianFodor

2023-12-19 13:37 UTC, paulmultiversx approved these changes

2023-12-20 14:06 UTC, CristianFodor commented
{"address":"erd1qkfnucxmuxgevllj9j234j9cqqktcnwqtff8ps9vg0fzupzf0zvstpgrkv","message":"0x30636462613531386465303231313261666230643939663938653832383638393937393537623563","signature":"0x347a384499bef4150cd105899b0aa3fb1726b8ccce26513bcbff61ed0bcce5d0795b96366e25a840a91ca171361fa9f6ceabdf9b8622a2ee2c7124256f866900","version":1,"signer":"ErdJS"}

2023-12-21 11:49 UTC, paulmultiversx requested changes
Hey, @CristianFodor.

Please copy-paste in the comments only this line as the signature confirmation: 

0x347a384499bef4150cd105899b0aa3fb1726b8ccce26513bcbff61ed0bcce5d0795b96366e25a840a91ca171361fa9f6ceabdf9b8622a2ee2c7124256f866900

Thanks.

2023-12-26 23:27 UTC, CristianFodor commented
0x347a384499bef4150cd105899b0aa3fb1726b8ccce26513bcbff61ed0bcce5d0795b96366e25a840a91ca171361fa9f6ceabdf9b8622a2ee2c7124256f866900

2023-12-27 14:27 UTC, paulmultiversx approved these changes

2023-12-28 10:36 UTC, merged