Add assets for 'FLA-e4ac51'
multiversx/mx-assets pull request #1896
Opened 2024-01-03 14:13 UTC by radubirsan

2024-01-04 13:46 UTC, paulmultiversx approved these changes

2024-01-04 13:49 UTC, paulmultiversx requested changes
Hey, @radubirsan.

Your logo is too large.
File tokens/FLA-e4ac51/logo.svg is too large! (302 KB)

logo.svg (must be in a square format)
logo.png (must have a resolution of 200x200 pixels)  
max size 100KB

Please reupload it properly before we can proceed with the merging of this PR.
Thanks.

2024-01-05 15:06 UTC, radubirsan commented
ok I made the svg smaller 91KB

2024-01-05 15:08 UTC, paulmultiversx approved these changes

2024-01-05 15:09 UTC, merged