Burnify: Guilds branding
multiversx/mx-assets pull request #1902
Opened 2024-01-04 21:19 UTC by bogdanIuga

2024-01-05 09:34 UTC, paulmultiversx approved these changes

2024-01-05 09:35 UTC, paulmultiversx requested changes
Hey, @bogdanIuga.

Using the owner address of the identity, please sign/use the (Message Signing feature). It represents the latest commit hash of this PR. You should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

2024-01-23 18:45 UTC, bogdanIuga commented
{"address":"erd1kpxe45qptessnl0vqgenw054gvmynwc4uslnkknc84rqyy95p4ssg9am4z","message":"0x32343565663039653339373561386466353034336332363632356234373262663835646133623035","signature":"0x22636199a92bc425b49b67ce3c4fb7620fdb2c15f51f7062d826fd42aab49845bf16bba04822dfabc887cd15b108b1ada5ab9cadf362e8f9cab9b50f01d1fb04","version":1,"signer":"ErdJS"}

2024-01-24 09:58 UTC, paulmultiversx approved these changes

2024-01-24 09:58 UTC, merged