Delete testnet/identities/twinsoft directory
multiversx/mx-assets pull request #1951
Opened 2024-01-22 15:07 UTC by sorinfederiga

Agency no longer exists

2024-01-29 11:58 UTC, paulmultiversx approved these changes

2024-01-29 12:01 UTC, paulmultiversx requested changes
Hi, @sorinfederiga.

Using the owner address of the identity, please sign/use the (Message Signing feature).

It represents the latest commit hash of this PR. 

Using our Utils dApp you should add a comment to this PR with the obtained signature. 

This is a step that ensures the ownership of the address. 

After that, we will be able to merge this PR.

Thanks.

2024-01-29 15:02 UTC, paulmultiversx approved these changes

2024-02-02 15:44 UTC, paulmultiversx commented
Hey, @sorinfederiga.

At the time of writing, this is the latest commit hash you need to sign: 42e766f1aa021f2e7a7230b652da51206f75909c

Using our Utils dApp you should add a comment to this PR with the obtained signature.

Thanks.

2024-02-02 17:11 UTC, sorinfederiga commented
0x190b1224735eb2f3abb8e722f410b5d475238b681676c44cd21ec0ccb6d5c7ba7b2762496dda0f21d7c3f22b73d4fab0e85790d85257de6d8ca3a4a15fb3de02

2024-02-20 14:01 UTC, closed without merging