Add files via upload
multiversx/mx-assets pull request #1953
Opened 2024-01-22 20:44 UTC by AlpineSafeStaking

2024-01-24 09:59 UTC, paulmultiversx requested changes
Hi, @AlpineSafeStaking.

Using the owner address of the identity, please sign/use the (Message Signing feature). It represents the latest commit hash of this PR. You should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

2024-01-24 18:43 UTC, AlpineSafeStaking commented
0xd2af330a8821b1af1cca21068e42d36f17741ba36afac3af24c9340cdb1ddb8013057b995715b1217f8a1486cdc8b48f9f9919ca34f20fd573707bfb591e0b07

2024-01-29 08:56 UTC, paulmultiversx approved these changes

2024-01-29 09:01 UTC, paulmultiversx commented
Hey, @AlpineSafeStaking.

Using the owner address of the identity, please sign/use the (Message Signing feature). It represents the latest commit hash of this PR. Using our Utils dApp you should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

2024-02-07 10:44 UTC, merged