XBIDWEGLD-6469b8 Token Branding
multiversx/mx-assets pull request #2061
Opened 2024-02-19 15:51 UTC by IonutCioarec

2024-02-19 16:17 UTC, paulmultiversx approved these changes

2024-02-19 16:27 UTC, paulmultiversx requested changes
Hi, @IonutCioarec.

Please provide a signature for the latest commit sha: `003df805e6b1c64ae829025d64c38e9d644387ec` which must be signed with the owner wallet address.

Thanks.

2024-02-19 18:08 UTC, tanghel commented
0xb628e126fc4e27c9aa4ac03486493ca44b29435649aad1298911b97df2f90e8f80d25218288998f835aa1d0b45da116a71b838d3a23207010364432b75e5760f

2024-02-20 08:05 UTC, paulmultiversx approved these changes

2024-02-20 08:05 UTC, merged