Add assets for 'fourytytwoag'
multiversx/mx-assets pull request #2063
Opened 2024-02-19 23:45 UTC by FourtyTwoAG

2024-02-20 12:44 UTC, paulmultiversx approved these changes

2024-02-20 12:46 UTC, paulmultiversx requested changes
Hey, @FourtyTwoAG.

Please provide a signature for the latest commit sha: `bd1e190ef6eada6af5bc969708e4e28c260312ea` which must be signed with the owner wallet address: 
`erd1yj98hu0ccea0praq0u2kwgefk28aelgjcjsamt9eqkugsarqz7rswfs8xj`

Feel free to use the Sign Message feature from the Utils dApp: https://utils.multiversx.com/

Thanks.

2024-05-27 21:38 UTC, FourtyTwoAG commented
{"address":"erd1yj98hu0ccea0praq0u2kwgefk28aelgjcjsamt9eqkugsarqz7rswfs8xj","message":"0x62643165313930656636656164613661663562633936393730386534653238633236303331326561","signature":"0x2b3a26f455dc0c0ce47e48a842b458cc4e1f5dfcfd32ef0cb5d71979c35f3c3ebf96f538680358809a29ec0493ffb7c82afbfe27a1347495cf6c31d166f1a30d","version":1,"signer":"ErdJS"}

2024-05-28 06:56 UTC, paulmultiversx approved these changes

2024-05-28 06:57 UTC, merged