Add assets for 'orius'
multiversx/mx-assets pull request #2071
Opened 2024-02-20 14:13 UTC by Orius

2024-02-20 14:27 UTC, paulmultiversx approved these changes

2024-02-20 14:30 UTC, paulmultiversx requested changes
Hi, @Orius.

Please provide a signature for the latest commit sha: `fe8f01998ce63435ac8433967f9b1526e720d8bb` which must be signed with the owner wallet address: 
`erd18mnega9zvycjulru38utjy7anzetgg63zgvhqerpyyqqwvad552qlzjpf7`

Feel free to use the Sign Message feature from the Utils dApp: https://utils.multiversx.com/

Thanks.

2024-02-20 14:34 UTC, Orius commented
> Hi, @Orius.
> 
> Please provide a signature for the latest commit sha: `fe8f01998ce63435ac8433967f9b1526e720d8bb` which must be signed with the owner wallet address: `erd18mnega9zvycjulru38utjy7anzetgg63zgvhqerpyyqqwvad552qlzjpf7`
> 
> Feel free to use the Sign Message feature from the Utils dApp: https://utils.multiversx.com/
> 
> Thanks.

{
  "address": "erd18mnega9zvycjulru38utjy7anzetgg63zgvhqerpyyqqwvad552qlzjpf7",
  "message": "0x66653866303139393863653633343335616338343333393637663962313532366537323064386262",
  "signature": "0x2f4f8c1c624173d44023950e6e2039dee8128d698414d925c6206f9ac1eb4c90007ffdc16a50e3ed438d4de2dfd03f59e3410f3cd3d9f51b11cdf45536120008",
  "version": 1,
  "signer": "ErdJS"
}

2024-02-20 16:20 UTC, paulmultiversx approved these changes

2024-02-21 16:08 UTC, Orius commented
{
"address": "erd18mnega9zvycjulru38utjy7anzetgg63zgvhqerpyyqqwvad552qlzjpf7",
"message": "0x66653866303139393863653633343335616338343333393637663962313532366537323064386262",
"signature": "0x2f4f8c1c624173d44023950e6e2039dee8128d698414d925c6206f9ac1eb4c90007ffdc16a50e3ed438d4de2dfd03f59e3410f3cd3d9f51b11cdf45536120008",
"version": 1,
"signer": "ErdJS"
}

2024-02-22 08:36 UTC, paulmultiversx approved these changes

2024-02-22 08:38 UTC, merged