Add assets for 'SHM-c8e063'
multiversx/mx-assets pull request #2099
Opened 2024-02-29 12:31 UTC by ZeinelShawarma

2024-02-29 16:13 UTC, paulmultiversx requested changes
Hi, @ZeinelShawarma.

Please provide a signature for the latest commit sha: `ee715ea89408370ad3d60fff5c6364e05c3ade95` which must be signed with the owner wallet address: 
`erd1c2psx9q4gha093yv670th4quw2svfc83ejcrsas90ffqetxx3kdq6nl8xe`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

2024-02-29 17:25 UTC, ZeinelShawarma commented
Here you are: 8da638e808f4ddf29746c991514211011e36554d3e562c0b87e822228441770b05c00ccabe0c57a1a9201cda43b6527d159b1cefebf09e1be82beb974de4f90c

https://utils.multiversx.com/sign-message?message=ee715ea89408370ad3d60fff5c6364e05c3ade95&address=erd1c2psx9q4gha093yv670th4quw2svfc83ejcrsas90ffqetxx3kdq6nl8xe&signature=8da638e808f4ddf29746c991514211011e36554d3e562c0b87e822228441770b05c00ccabe0c57a1a9201cda43b6527d159b1cefebf09e1be82beb974de4f90c&status=signed

2024-03-01 10:19 UTC, paulmultiversx approved these changes

2024-03-01 10:20 UTC, paulmultiversx requested changes
Hey, @ZeinelShawarma.

Please provide only the signature in a new comment.

Thanks.

2024-03-01 13:20 UTC, paulmultiversx approved these changes

2024-03-01 13:52 UTC, merged