Add assets for 'MAGAX-2c0d20'
multiversx/mx-assets pull request #2187
Opened 2024-03-13 05:49 UTC by cryptoprosnetwork

2024-03-13 12:20 UTC, paulmultiversx approved these changes

2024-03-13 12:21 UTC, paulmultiversx requested changes
Hi, @cryptoprosnetwork 

Please provide a signature for the latest commit sha: `703078e29ee91626dde0e5da3900647f383014c8` which must be signed with the owner wallet address: 
`erd19gy2z84l5sh3mrtarywwlgmurcxn8hz8vytvupnkke0dzlmuhfxsvz52qt`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

2024-03-14 10:05 UTC, paulmultiversx approved these changes

2024-03-14 10:06 UTC, paulmultiversx commented
Hi, @cryptoprosnetwork.

If you don't add your signature in a comment, this PR can not pass the checks.

2024-03-14 18:33 UTC, cryptoprosnetwork commented
8ab09dab953eba26697daccc82563176f8f3c0bfd8888d6d38b1a2b49530f00dfca568e3577ae3f09b8d2d5abe6d21137304286f3901c56aa01ddfa6d863f00f

2024-03-15 09:53 UTC, merged