Add eglstakingprovider.com
multiversx/mx-assets pull request #3008
Opened 2024-06-11 13:25 UTC by egldstakingprovidercom

2024-06-12 07:27 UTC, paulmultiversx submitted a review, later dismissed

2024-06-12 07:36 UTC, bogdan-rosianu requested changes

2024-06-12 07:36 UTC, bogdan-rosianu commented on identities/egldstakingprovider/info.json
> +    "erd1wm5e209ty5tv29egc82rg6shun2lll3evsth9pw4n64yz55dw3xs6qtgum" // staking provider address
JSON does not accept comments. please remove `// staking provider address`

2024-06-13 07:44 UTC, paulmultiversx approved these changes

2024-06-13 07:46 UTC, bogdan-rosianu approved these changes

2024-06-13 07:47 UTC, merged